server {
  listen 80;
  server_name _;
  client_max_body_size 50m;

  location /_next/static/ {
    proxy_pass http://next:3000;
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  location /api/ {
    proxy_pass http://api:8080;
    include /etc/nginx/conf.d/proxy.inc;
  }

  location /assets/ {
    proxy_pass http://api:8080;
    include /etc/nginx/conf.d/proxy.inc;
  }

  location / {
    proxy_pass http://next:3000;
    include /etc/nginx/conf.d/proxy.inc;
  }
}
